### ISSUE TITLE
libresonic support?

### ISSUE THREAD

**Issue by anarcat** [mschuerig/subsonic-docker-image#14]
Hi,

I have modified this container to work with libresonic as well, in my [libresonic](https://github.com/anarcat/subsonic-docker-image/tree/libresonic) branch. I am not sure how to deal with this - i guess I could just keep my repository for libresonic and keep your for subsonic? or would you like to maintain a branch for libresonic? how do we deal with such things in docker normally?

notice how I dropped the startup.sh script. it's partly out of laziness: i didn't want to figure out which flags are supported by libresonic. but it also seems a lot simpler and allows users to pass their own arguments directly on the commandline without having to convert them. upstream documentation then applies directly...

**Comment by mschuerig** [comment]
Hi anarcat,

I wasn't aware of libresonic until now and after a first look, I may even start to use it myself instead of subsonic. However, I'll have to look into it more thoroughly and it can take some time, possibly two weeks, until I get to it.

**Comment by anarcat** [comment]
that's nice to hear!

**Comment by mschuerig** [comment]
Hi anarcat,

I've had a look at your changes for libresonic. Right now I won't do anything with them. But over time the most likely outcome is that I stop maintaining the subsonic docker image and switch to your libresonic version.

**Comment by anarcat** [comment]
alright! i don't use it myself either, to be honest. ;) but i will within the next few weeks and I'll let you know how it goes1

**Comment by anarcat** [comment]
FWIW, i switched to libresonic and then to airsonic. the airsonic branch here refactors the Dockerfile to make it easier to switch between the (!) 3:

https://github.com/anarcat/subsonic-docker-image/tree/airsonic

notice how everything is set on top of the file for easier modification...

**Comment by anarcat** [comment]
ping?

**Comment by mschuerig** [comment]
I'm sorry to say that I'm currently not using subsonic or similar anymore. Please just go ahead with your fork.

**Comment by anarcat** [comment]
@mschuerig thanks for the update. I've created https://github.com/anarcat/docker-airsonic for the future, thanks for your work!
